const translations = {
    es: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "IDIOMA",
        lbl_edition: "ACTOR MEXICANO",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "CONOCEME",
        btn_portafolio: "PORTAFOLIO DE IMAGENES",
        btn_poder_musica: "VIDEOS DE MI TRAYECTORIA",
        btn_contacto: "REDES SOCIALES",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "CLIC PARA REPRODUCIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toca una imagen para ampliarla y deslizarla",
        btn_cerrar: "Cerrar",
        btn_comparte_historia: "COMPARTIR",
        lbl_producido_por: "PRODUCIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTÁCTANOS",
        lbl_biografia: "Biografía",
        lbl_nombre_label: "Nombre:",
        val_nombre: "Iñaki Godoy Jasso",
        lbl_edad_label: "Edad:",
        val_edad: "22 años",
        lbl_nacimiento_label: "Nacimiento:",
        val_nacimiento: "25 Ago / Ciudad de México",
        lbl_nacionalidad_label: "Nacionalidad:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estatura / Actividad:",
        val_estatura: "1.70 m / Actuación Global",
        lbl_formacion_titulo: "Formación Profesional",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Actor de Cine, Teatro y Televisión de Proyección Internacional.",
        lbl_desempeno_label: "Desempeño:",
        val_desempeno_text: "Versatilidad dramática, carisma desbordante, entrega absoluta y profunda sensibilidad artística en cada personaje.",
        lbl_especialidad_titulo: "Especialidad",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Interpretación Protagónica y Construcción de Personajes Icónicos.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Dominio de la expresión escénica, capacidad de conectar genuinamente con audiencias globales y liderazgo escénico natural.",
        lbl_logros_titulo: "Logros y Trayectoria",
        val_logro_1: "📌 Protagonista mundial como <strong>Monkey D. Luffy</strong> en la aclamada serie de acción real de Netflix <strong>\"One Piece\"</strong>, conquistando la admiración internacional.",
        val_logro_2: "🥇 Consolidación estelar en producciones de alto impacto de streaming como <strong>\"El Dragón: El regreso de un guerrero\"</strong> y <strong>\"¿Quién mató a Sara?\"</strong>.",
        val_logro_3: "🌐 Máximo embajador del talento actoral mexicano contemporáneo, inspirando a nuevas generaciones con su inquebrantable pasión, calidad humana y optimismo inagotable.",
        btn_regresar_menu: "REGRESAR AL MENÚ 🚀",
        contact_title: "REDES SOCIALES",
        contact_contracting: "Redes sociales",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "ESCANEA EL CÓDIGO QR",
        btn_share_qr: "COMPARTIR QR",
        cat2_t: "PORTAFOLIO DE IMAGENES",
        cat2_c: "Trabaja cada día en su preparación actoral y mental, aplicando una mentalidad de cero límites y perfeccionando cada interpretación para llevar el nombre de México a lo más alto.",
        cat3_t: "VIDEOS DE MI TRAYECTORIA",
        cat3_c: "Su mayor fortaleza es la resiliencia mental combinada con la disciplina absoluta en cada interpretación.",
        lbl_mis_fortalezas: "México en el corazón",
        btn_tributo_tri: "Asi llegué a ONE PIECE",
        btn_junto_mar: "Me enteré de que sería Luffy",
        btn_con_gente: "En ONE PIECE",
        btn_cantando_beatles: "Iñaki de niño",
        btn_video_historia: "MI HISTORIA",
        btn_ver_detalles: "VER DETALLES"
    },
    en: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "LANGUAGE",
        lbl_edition: "MEXICAN ACTOR",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "ABOUT ME",
        btn_portafolio: "IMAGE PORTFOLIO",
        btn_poder_musica: "CAREER VIDEOS",
        btn_contacto: "SOCIAL MEDIA",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "CLICK TO PLAY",
        btn_grandes_momentos: "GREAT MOMENTS",
        modal_grandes_momentos_title: "GREAT MOMENTS",
        modal_grandes_momentos_desc: "Tap an image to zoom and swipe",
        btn_cerrar: "Close",
        btn_comparte_historia: "SHARE",
        lbl_producido_por: "PRODUCED BY \"TALENT CARD\"",
        btn_contactanos_card: "CONTACT US",
        lbl_biografia: "Biography",
        lbl_nombre_label: "Name:",
        val_nombre: "Iñaki Godoy Jasso",
        lbl_edad_label: "Age:",
        val_edad: "22 years old",
        lbl_nacimiento_label: "Birth:",
        val_nacimiento: "Aug 25 / Mexico City",
        lbl_nacionalidad_label: "Nationality:",
        val_nacionalidad: "Mexican",
        lbl_estatura_label: "Height / Activity:",
        val_estatura: "1.70 m / Global Acting",
        lbl_formacion_titulo: "Professional Training",
        lbl_perfil_label: "Profile:",
        val_perfil_text: "Film, Theater, and Television Actor with International Projection.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "Dramatic versatility, overflowing charisma, absolute dedication, and deep artistic sensitivity in every character.",
        lbl_especialidad_titulo: "Specialty",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Leading Interpretation and Construction of Iconic Characters.",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "Mastery of stage expression, ability to genuinely connect with global audiences, and natural stage leadership.",
        lbl_logros_titulo: "Achievements & Career",
        val_logro_1: "📌 Global protagonist as <strong>Monkey D. Luffy</strong> in Netflix's acclaimed live-action series <strong>\"One Piece\"</strong>, winning international admiration.",
        val_logro_2: "🥇 Stellar consolidation in high-impact streaming productions such as <strong>\"The Dragon: Return of a Warrior\"</strong> and <strong>\"Who Killed Sara?\"</strong>.",
        val_logro_3: "🌐 Ultimate ambassador of contemporary Mexican acting talent, inspiring new generations with his unwavering passion, human quality, and boundless optimism.",
        btn_regresar_menu: "BACK TO MENU 🚀",
        contact_title: "SOCIAL MEDIA",
        contact_contracting: "Social media",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "SCAN THE QR CODE",
        btn_share_qr: "SHARE QR",
        cat2_t: "IMAGE PORTFOLIO",
        cat2_c: "He works every day on his acting and mental preparation, applying a zero-limits mindset and perfecting every performance to bring Mexico's name to the very top.",
        cat3_t: "CAREER VIDEOS",
        cat3_c: "His greatest strength is mental resilience combined with absolute discipline in every performance.",
        lbl_mis_fortalezas: "Mexico in the heart",
        btn_tributo_tri: "How I got to ONE PIECE",
        btn_junto_mar: "I found out I was going to be Luffy",
        btn_con_gente: "In ONE PIECE",
        btn_cantando_beatles: "Iñaki as a child",
        btn_video_historia: "MY STORY",
        btn_ver_detalles: "VIEW DETAILS"
    },
    pt: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "IDIOMA",
        lbl_edition: "ATOR MEXICANO",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "SOBRE MIM",
        btn_portafolio: "PORTFÓLIO DE IMAGENS",
        btn_poder_musica: "VÍDEOS DA MINHA TRAJETÓRIA",
        btn_contacto: "REDES SOCIAIS",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "CLIQUE PARA REPRODUZIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toque em uma imagem para ampliar e deslizar",
        btn_cerrar: "Fechar",
        btn_comparte_historia: "COMPARTILHAR",
        lbl_producido_por: "PRODUZIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTATE-NOS",
        lbl_biografia: "Biografia",
        lbl_nombre_label: "Nome:",
        val_nombre: "Iñaki Godoy Jasso",
        lbl_edad_label: "Idade:",
        val_edad: "22 anos",
        lbl_nacimiento_label: "Nascimento:",
        val_nacimiento: "25 Ago / Cidade do México",
        lbl_nacionalidad_label: "Nacionalidade:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Altura / Atividade:",
        val_estatura: "1,70 m / Atuação Global",
        lbl_formacion_titulo: "Formação Profissional",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Ator de Cinema, Teatro e Televisão de Projeção Internacional.",
        lbl_desempeno_label: "Desempenho:",
        val_desempeno_text: "Versatilidade dramática, carisma transbordante, entrega absoluta e profunda sensibilidade artística em cada personagem.",
        lbl_especialidad_titulo: "Especialidade",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Interpretação Protagonista e Construção de Personagens Icônicos.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Domínio da expressão cênica, capacidade de conectar-se genuinamente com o público global e liderança cênica natural.",
        lbl_logros_titulo: "Conquistas e Trajetória",
        val_logro_1: "📌 Protagonista mundial como <strong>Monkey D. Luffy</strong> na aclamada série live-action da Netflix <strong>\"One Piece\"</strong>, conquistando admiração internacional.",
        val_logro_2: "🥇 Consolidação estelar em produções de streaming de alto impacto como <strong>\"O Dragão: O Retorno de um Guerreiro\"</strong> e <strong>\"Quem Matou Sara?\"</strong>.",
        val_logro_3: "🌐 Maior embaixador do talento de atuação mexicano contemporâneo, inspirando novas gerações com sua paixão inabalável, qualidade humana e otimismo inesgotável.",
        btn_regresar_menu: "VOLTAR AO MENU 🚀",
        contact_title: "REDES SOCIAIS",
        contact_contracting: "Redes sociais",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "ESCANEIE O CÓDIGO QR",
        btn_share_qr: "COMPARTILHAR QR",
        cat2_t: "PORTFÓLIO DE IMAGENS",
        cat2_c: "Ele trabalha todos os dias em sua preparação artística e mental, aplicando uma mentalidade de zero limites e aperfeiçoando cada atuação para levar o nome do México ao topo.",
        cat3_t: "VÍDEOS DA MINHA TRAJETÓRIA",
        cat3_c: "Sua maior força é a resiliência mental combinada com disciplina absoluta em cada interpretação.",
        lbl_mis_fortalezas: "México no coração",
        btn_tributo_tri: "Como cheguei a ONE PIECE",
        btn_junto_mar: "Fiquei sabendo que seria o Luffy",
        btn_con_gente: "Em ONE PIECE",
        btn_cantando_beatles: "Iñaki quando criança",
        btn_video_historia: "MINHA HISTÓRIA",
        btn_ver_detalles: "VER DETALHES"
    },
    fr: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "LANGUE",
        lbl_edition: "ACTEUR MEXICAIN",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "À PROPOS",
        btn_portafolio: "PORTEFEUILLE D'IMAGES",
        btn_poder_musica: "VIDÉOS DE MA CARRIÈRE",
        btn_contacto: "RÉSEAUX SOCIAUX",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "CLIQUEZ POUR LIRE",
        btn_grandes_momentos: "GRANDS MOMENTS",
        modal_grandes_momentos_title: "GRANDS MOMENTOS",
        modal_grandes_momentos_desc: "Appuyez sur une image pour l'agrandir et balayer",
        btn_cerrar: "Fermer",
        btn_comparte_historia: "PARTAGER",
        lbl_producido_por: "PRODUIT PAR \"TALENT CARD\"",
        btn_contactanos_card: "CONTACTEZ-NOUS",
        lbl_biografia: "Biographie",
        lbl_nombre_label: "Nom :",
        val_nombre: "Iñaki Godoy Jasso",
        lbl_edad_label: "Âge :",
        val_edad: "22 ans",
        lbl_nacimiento_label: "Naissance :",
        val_nacimiento: "25 Aoû / Ville de Mexico",
        lbl_nacionalidad_label: "Nationalité :",
        val_nacionalidad: "Mexicaine",
        lbl_estatura_label: "Taille / Activité :",
        val_estatura: "1,70 m / Acteur Global",
        lbl_formacion_titulo: "Formation Professionnelle",
        lbl_perfil_label: "Profil :",
        val_perfil_text: "Acteur de Cinéma, Théâtre et Télévision à Projection Internationale.",
        lbl_desempeno_label: "Performance :",
        val_desempeno_text: "Polyvalence dramatique, charisme débordant, engagement absolu et profonde sensibilité artistique dans chaque personnage.",
        lbl_especialidad_titulo: "Spécialité",
        lbl_disciplina_label: "Discipline :",
        val_disciplina_text: "Interprétation Principale et Construction de Personnages Iconiques.",
        lbl_tecnica_label: "Technique :",
        val_tecnica_text: "Maîtrise de l'expression scénique, capacité à se connecter authentiquement avec les publics mondiaux et leadership scénique naturel.",
        lbl_logros_titulo: "Réalisations et Parcours",
        val_logro_1: "📌 Protagoniste mondial dans le rôle de <strong>Monkey D. Luffy</strong> dans la série live-action acclamée de Netflix <strong>\"One Piece\"</strong>, conquérant l'admiration internationale.",
        val_logro_2: "🥇 Consolidation stellaire dans des productions en streaming à fort impact telles que <strong>\"Le Dragon : Le Retour d'un Guerrier\"</strong> et <strong>\"Qui a tué Sara ?\"</strong>.",
        val_logro_3: "🌐 Ambassadeur ultime du talent d'acteur mexicain contemporain, inspirant de nouvelles générations avec sa passion inébranlable, sa qualité humaine et son optimisme inépuisable.",
        btn_regresar_menu: "RETOOUR AU MENU 🚀",
        contact_title: "RÉSEAUX SOCIAUX",
        contact_contracting: "Réseaux sociaux",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "SCANNEZ LE CODE QR",
        btn_share_qr: "PARTAGER LE QR",
        cat2_t: "PORTEFEUILLE D'IMAGES",
        cat2_c: "Il travaille chaque jour sur sa préparation d'acteur et mentale, appliquant une mentalité sans limites et perfectionnant chaque interprétation pour porter le nom du Mexique au sommet.",
        cat3_t: "VIDÉOS DE MA CARRIÈRE",
        cat3_c: "Sa plus grande force est la résilience mentale combinée à une discipline absolue dans chaque interprétation.",
        lbl_mis_fortalezas: "Le Mexique dans le cœur",
        btn_tributo_tri: "Comment je suis arrivé à ONE PIECE",
        btn_junto_mar: "J'ai su que je serais Luffy",
        btn_con_gente: "Dans ONE PIECE",
        btn_cantando_beatles: "Iñaki enfant",
        btn_video_historia: "MON HISTOIRE",
        btn_ver_detalles: "VOIR LES DÉTAILS"
    },
    ko: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "언어",
        lbl_edition: "멕시코 배우",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "프로필 소개",
        btn_portafolio: "이미지 포트폴리오",
        btn_poder_musica: "경력 영상",
        btn_contacto: "소셜 미디어",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "재생하려면 클릭",
        btn_grandes_momentos: "주요 순간들",
        modal_grandes_momentos_title: "주요 순간들",
        modal_grandes_momentos_desc: "이미지를 터치하여 확대하고 슬라이드하세요",
        btn_cerrar: "닫기",
        btn_comparte_historia: "공유하기",
        lbl_producido_por: "제작: \"TALENT CARD\"",
        btn_contactanos_card: "문의하기",
        lbl_biografia: "전기",
        lbl_nombre_label: "이름:",
        val_nombre: "이냐키 고도이 하소",
        lbl_edad_label: "나이:",
        val_edad: "22세",
        lbl_nacimiento_label: "출생:",
        val_nacimiento: "8월 25일 / 멕시코시티",
        lbl_nacionalidad_label: "국적:",
        val_nacionalidad: "멕시코",
        lbl_estatura_label: "신장 / 활동:",
        val_estatura: "1.70 m / 글로벌 연기 활동",
        lbl_formacion_titulo: "전문 교육",
        lbl_perfil_label: "프로필:",
        val_perfil_text: "국제적인 무대를 지향하는 영화, 연극, 텔레비전 배우.",
        lbl_desempeno_label: "역량:",
        val_desempeno_text: "모든 캐릭터에서 드러나는 극적인 다재다능함, 넘치는 카리스마, 절대적인 헌신 및 깊은 예술적 감수성.",
        lbl_especialidad_titulo: "전문 분야",
        lbl_disciplina_label: "분야:",
        val_disciplina_text: "주연 연기 및 상징적인 캐릭터 구축.",
        lbl_tecnica_label: "테크닉:",
        val_tecnica_text: "무대 표현력 통달, 글로벌 관객과 진정성 있게 교감하는 능력, 그리고 자연스러운 무대 리더십.",
        lbl_logros_titulo: "성과 및 경력",
        val_logro_1: "📌 넷플릭스의 극찬받은 실사 시리즈 <strong>\"원피스\"</strong>에서 <strong>몽키 D. 루피</strong> 역으로 전 세계적인 주인공을 맡아 국제적인 찬사를 받았습니다.",
        val_logro_2: "🥇 <strong>\"엘 드라곤: 전사의 귀환\"</strong> 및 <strong>\"누가 사라를 죽였을까?\"</strong>와 같은 고영향력 스트리밍 프로덕션에서의 스타 주연 확립.",
        val_logro_3: "🌐 흔들리지 않는 열정, 인간적 품성, 끝없는 낙관주의로 새로운 세대에게 영감을 주는 현대 멕시코 연기 예술의 최고의 홍보대사.",
        btn_regresar_menu: "메뉴로 돌아가기 🚀",
        contact_title: "소셜 미디어",
        contact_contracting: "소셜 미디어",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "QR 코드를 스캔하세요",
        btn_share_qr: "QR 공유",
        cat2_t: "이미지 포트폴리오",
        cat2_c: "그는 한계가 없는 마음가짐을 적용하고 멕시코의 이름을 가장 높이 올리기 위해 모든 연기를 다듬으며 매일 연기 및 정신적 준비에 힘쓰고 있습니다.",
        cat3_t: "경력 영상",
        cat3_c: "그의 가장 큰 장점은 정신적 회복력과 모든 연기에서의 절대적인 규율이 결합된 것입니다.",
        lbl_mis_fortalezas: "마음속의 멕시코",
        btn_tributo_tri: "원피스에 합류하게 된 계기",
        btn_junto_mar: "루피가 될 것을 알게 되었을 때",
        btn_con_gente: "원피스에서",
        btn_cantando_beatles: "어린 시절의 이냐키",
        btn_video_historia: "나의 이야기",
        btn_ver_detalles: "자세히 보기"
    },
    de: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "SPRACHE",
        lbl_edition: "MEXIKANISCHER SCHAUSPIELER",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "ÜBER MICH",
        btn_portafolio: "BILDER-PORTFOLIO",
        btn_poder_musica: "KARRIEREVIDEOS",
        btn_contacto: "SOZIALE MEDIEN",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "KLICKEN ZUM ABSPIELEN",
        btn_grandes_momentos: "GROSSE MOMENTE",
        modal_grandes_momentos_title: "GROSSE MOMENTE",
        modal_grandes_momentos_desc: "Tippen Sie auf ein Bild, um es zu zoomen und zu wischen",
        btn_cerrar: "Schließen",
        btn_comparte_historia: "TEILEN",
        lbl_producido_por: "PRODUZIERT VON \"TALENT CARD\"",
        btn_contactanos_card: "KONTAKTIEREN SIE UNS",
        lbl_biografie: "Biografie",
        lbl_nombre_label: "Name:",
        val_nombre: "Iñaki Godoy Jasso",
        lbl_edad_label: "Alter:",
        val_edad: "22 Jahre",
        lbl_nacimiento_label: "Geburtstag:",
        val_nacimiento: "25. Aug. / Mexiko-Stadt",
        lbl_nacionalidad_label: "Nationalität:",
        val_nacionalidad: "Mexikanisch",
        lbl_estatura_label: "Größe / Tätigkeit:",
        val_estatura: "1,70 m / Globales Schauspiel",
        lbl_formacion_titulo: "Professionelle Ausbildung",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Film-, Theater- und Fernsehschauspieler mit internationaler Ausrichtung.",
        lbl_desempeno_label: "Leistung:",
        val_desempeno_text: "Dramatische Vielseitigkeit, überschäumendes Charisma, absolute Hingabe und tiefe künstlerische Sensibilität in jeder Rolle.",
        lbl_especialidad_titulo: "Spezialität",
        lbl_disciplina_label: "Disziplin:",
        val_disciplina_text: "Hauptdarstellung und Konstruktion ikonischer Charaktere.",
        lbl_tecnica_label: "Technik:",
        val_tecnica_text: "Beherrschung des Bühnenausdrucks, Fähigkeit zur echten Verbindung mit globalen Publikumsschichten und natürlicher Bühnenführerschaft.",
        lbl_logros_titulo: "Erfolge und Werdegang",
        val_logro_1: "📌 Weltweiter Protagonist als <strong>Monkey D. Luffy</strong> in der gefeierten Netflix-Live-Action-Serie <strong>\"One Piece\"</strong>, womit er internationale Bewunderung gewann.",
        val_logro_2: "🥇 Sternhafte Festigung in hochwirksamen Streaming-Produktionen wie <strong>\"El Dragón: Die Rückkehr eines Kriegers\"</strong> und <strong>\"Wer hat Sara ermordet?\"</strong>.",
        val_logro_3: "🌐 Ultimativer Botschafter des zeitgenössischen mexikanischen Schauspieltalents, der neue Generationen mit seiner unerschütterlichen Leidenschaft, menschlichen Qualität und unermesslichen Optimismus inspiriert.",
        btn_regresar_menu: "ZURÜCK ZUM MENÜ 🚀",
        contact_title: "SOZIALE MEDIEN",
        contact_contracting: "Soziale Medien",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "QR-CODE SCANNEN",
        btn_share_qr: "QR TEILEN",
        cat2_t: "BILDER-PORTFOLIO",
        cat2_c: "Er arbeitet jeden Tag an seiner schauspielerischen und mentalen Vorbereitung, verfolgt eine Denkweise ohne Grenzen und perfektioniert jede Darstellung, um den Namen Mexikos ganz nach oben zu bringen.",
        cat3_t: "KARRIEREVIDEOS",
        cat3_c: "Seine größte Stärke ist mentale Belastbarkeit kombiniert mit absoluter Disziplin bei jeder Darbietung.",
        lbl_mis_fortalezas: "Mexiko im Herzen",
        btn_tributo_tri: "Wie ich zu ONE PIECE kam",
        btn_junto_mar: "Ich erfuhr, dass ich Luffy sein würde",
        btn_con_gente: "In ONE PIECE",
        btn_cantando_beatles: "Iñaki als Kind",
        btn_video_historia: "MEINE GESCHICHTE",
        btn_ver_detalles: "DETAILS ANSEHEN"
    },
    ja: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "言語",
        lbl_edition: "メキシコの俳優",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "私について",
        btn_portafolio: "画像ポートフォリオ",
        btn_poder_musica: "経歴動画",
        btn_contacto: "ソーシャルメディア",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "クリックして再生",
        btn_grandes_momentos: "重要な瞬間",
        modal_grandes_momentos_title: "重要な瞬間",
        modal_grandes_momentos_desc: "画像をタップして拡大・スライド",
        btn_cerrar: "閉じる",
        btn_comparte_historia: "シェア",
        lbl_producido_por: "制作: \"TALENT CARD\"",
        btn_contactanos_card: "お問い合わせ",
        lbl_biografia: "経歴",
        lbl_nombre_label: "名前：",
        val_nombre: "イニャキ・ゴドイ・ハッソ",
        lbl_edad_label: "年齢：",
        val_edad: "22歳",
        lbl_nacimiento_label: "誕生日：",
        val_nacimiento: "8月25日 / メキシコシティ",
        lbl_nacionalidad_label: "国籍：",
        val_nacionalidad: "メキシコ",
        lbl_estatura_label: "身長 / 活動：",
        val_estatura: "1.70 m / グローバル演技",
        lbl_formacion_titulo: "専門教育",
        lbl_perfil_label: "プロフィール：",
        val_perfil_text: "国際的な飛躍を目指す映画、舞台、テレビの俳優。",
        lbl_desempeno_label: "パフォーマンス：",
        val_desempeno_text: "劇的な多才さ、あふれるカリスマ性、絶対的な献身、そしてすべてのキャラクターにおける深い芸術的感受性。",
        lbl_especialidad_titulo: "専門分野",
        lbl_disciplina_label: "分野：",
        val_disciplina_text: "主役の解釈と象徴的なキャラクターの構築。",
        lbl_tecnica_label: "テクニック：",
        val_tecnica_text: "舞台表現の習得、世界中の観客と心から繋がる能力、そして自然な舞台上のリーダーシップ。",
        lbl_logros_titulo: "実績とキャリア",
        val_logro_1: "📌 ネットフリックスの絶賛された実写シリーズ<strong>「ONE PIECE」</strong>の<strong>モンキー・D・ルフィ</strong>役として世界的な主演を務め、国際的な賞賛を獲得。",
        val_logro_2: "🥇 <strong>「エル・ドラゴンの帰還」</strong>や<strong>「ズールーの秘密」</strong>などの影響力の高いストリーミング作品における輝かしい活躍。",
        val_logro_3: "🌐 揺るぎない情熱、人間性、尽きることのない楽観主義で新しい世代をインスパイアする、現代メキシコ演技才能の究極のアンバサダー。",
        btn_regresar_menu: "メニューに戻る 🚀",
        contact_title: "ソーシャルメディア",
        contact_contracting: "ソーシャルメディア",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "QRコードをスキャン",
        btn_share_qr: "QRをシェア",
        cat2_t: "画像ポートフォリオ",
        cat2_c: "彼はゼロ・リミットの精神を持ち、メキシコの誇りを最高峰に高めるために、演技とメンタルの準備に毎日取り組み、すべての表現を磨き上げています。",
        cat3_t: "経歴動画",
        cat3_c: "彼の最大の強みは、メンタルの回復力と、あらゆるパフォーマンスにおける絶対的な規律の融合です。",
        lbl_mis_fortalezas: "心の中にメキシコを",
        btn_tributo_tri: "ONE PIECEに出会うまで",
        btn_junto_mar: "ルフィ役に決まったと知った時",
        btn_con_gente: "ONE PIECEにて",
        btn_cantando_beatles: "子供の頃のイニャキ",
        btn_video_historia: "私のストーリー",
        btn_ver_detalles: "詳細を見る"
    },
    zh: {
        meta_title: "IÑAKI GODOY",
        lbl_idioma: "语言",
        lbl_edition: "墨西哥演员",
        lbl_hero_title: "IÑAKI GODOY",
        alt_hero_img: "Iñaki Godoy",
        btn_conoceme: "关于我",
        btn_portafolio: "图片作品集",
        btn_poder_musica: "演艺生涯视频",
        btn_contacto: "社交媒体",
        alt_video_thumb: "Video Preview",
        lbl_clic_reproducir: "点击播放",
        btn_grandes_momentos: "精彩时刻",
        modal_grandes_momentos_title: "精彩时刻",
        modal_grandes_momentos_desc: "点击图片放大并滑动查看",
        btn_cerrar: "关闭",
        btn_comparte_historia: "分享",
        lbl_producido_por: "由 \"TALENT CARD\" 制作",
        btn_contactanos_card: "联系我们",
        lbl_biografia: "生平简介",
        lbl_nombre_label: "姓名：",
        val_nombre: "伊尼亚基·戈多伊·哈索",
        lbl_edad_label: "年龄：",
        val_edad: "22岁",
        lbl_nacimiento_label: "出生：",
        val_nacimiento: "8月25日 / 墨西哥城",
        lbl_nacionalidad_label: "国籍：",
        val_nacionalidad: "墨西哥",
        lbl_estatura_label: "身高 / 活动：",
        val_estatura: "1.70米 / 全球演艺",
        lbl_formacion_titulo: "专业培训",
        lbl_perfil_label: "个人档案：",
        val_perfil_text: "具备国际知名度的电影、戏剧和电视演员。",
        lbl_desempeno_label: "表现：",
        val_desempeno_text: "戏剧多面性、溢出的个人魅力、绝对的奉献精神以及对每个角色的深刻艺术敏感度。",
        lbl_especialidad_titulo: "专业特长",
        lbl_disciplina_label: "学科：",
        val_disciplina_text: "领衔主演诠释与标志性角色塑造。",
        lbl_tecnica_label: "技术：",
        val_tecnica_text: "精通舞台表现力、与全球观众建立真诚情感连接的能力以及天生的舞台领导力。",
        lbl_logros_titulo: "成就与演艺生涯",
        val_logro_1: "📌 在备受好评的Netflix真人版剧集<strong>《海贼王》</strong>中全球主演<strong>蒙奇·D·路飞</strong>，赢得了国际间的赞誉。",
        val_logro_2: "🥇 在流媒体高影响力作品如<strong>《龙：一个战士的归还》</strong>和<strong>《谁杀了莎拉？》</strong>中确立了明星地位。",
        val_logro_3: "🌐 当代墨西哥演艺天赋的终极大使，以其坚定的激情、人文品质和不竭的乐观精神激励着新一代。",
        btn_regresar_menu: "返回菜单 🚀",
        contact_title: "社交媒体",
        contact_contracting: "社交媒体",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_tiktok: "TIKTOK",
        qr_heading: "扫描二维码",
        btn_share_qr: "分享二维码",
        cat2_t: "图片作品集",
        cat2_c: "他每天都在进行表演和心理上的准备，秉持零极限的心态，精雕细琢每一个演绎，将墨西哥的名字带向最高峰。",
        cat3_t: "演艺生涯视频",
        cat3_c: "他最大的优势是心理韧性与每一次演绎中绝对纪律的结合。",
        lbl_mis_fortalezas: "墨西哥在心中",
        btn_tributo_tri: "我是如何加入《海贼王》的",
        btn_junto_mar: "我知道自己将成为路飞的那一刻",
        btn_con_gente: "在《海贼王》中",
        btn_cantando_beatles: "童年的伊尼亚基",
        btn_video_historia: "我的故事",
        btn_ver_detalles: "查看详情"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const altElements = document.querySelectorAll('[data-i18n-alt]');
    altElements.forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute('alt', translations[lang][key]);
        }
    });

    if (translations[lang] && translations[lang]['meta_title']) {
        document.title = translations[lang]['meta_title'];
    }

    document.querySelectorAll('.lang-chip').forEach(chip => {
        chip.classList.remove('active');
        if (chip.getAttribute('onclick').includes(`'${lang}'`)) {
            chip.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'es';
    changeLanguage(savedLang);
});